name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # メインブランチに合わせてください

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # ここが重要！
          token: ${{ secrets.GH_TOKEN }}  # ここで認証を通す！

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Copy obsidian public files to docs
        run: |
          rm -rf docs/*
          cp -r obsidian/public/* docs/

      - name: Build Docusaurus
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
